<?php

/**
 * @file
 * Contains react_embed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_embed module.
    case 'help.page.react_embed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embeds a react component in Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function react_embed_theme() {
  return [
    'react_embed' => [
      // Not used but required.
      'variables' => ['component' => NULL],
    ],
  ];
}
